name: linting

on:
  pull_request:
    types: [opened, closed]

  workflow_dispatch:

env:
  GIST_ID: f1a5f45e1346698f50387619ff6c5bf7
  JSON_NAME: blender_uasset_addon_pylint_badge.json
   
jobs:
  linting:
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.x
          architecture: x64
          
      - uses: actions/checkout@v3
      
      - name: Install
        if: ${{github.event.pull_request.merged != true}}
        run: pip install flake8 pydocstyle
        
      - name: Run flake8
        if: ${{github.event.pull_request.merged != true}}
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run pydocstyle
        if: ${{github.event.pull_request.merged != true}}
        run: pydocstyle

      - name: Install
        run: pip install pylint
        
      - name: Run pylint
        run: python for_dev/lint.py --path=addons/blender_uasset_addon --file_name=${{ env.JSON_NAME }}

      - name: Update pylint badge status
        if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ env.GIST_ID }}
          file_path: ${{ env.JSON_NAME }}
          file_type: binary
